// <auto-generated />
using System;
using ERMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERMS.Migrations
{
    [DbContext(typeof(ERMSDbContext))]
    [Migration("20260213052950_sdd")]
    partial class sdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERMS.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "C-Level executives",
                            IsDeleted = false,
                            Name = "Executive"
                        },
                        new
                        {
                            Id = 2,
                            Description = "HR and talent management",
                            IsDeleted = false,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Software development and IT",
                            IsDeleted = false,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sales and business development",
                            IsDeleted = false,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Marketing and communications",
                            IsDeleted = false,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("ERMS.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.smith@company.com",
                            FirstName = "John",
                            HireDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            PhoneNumber = "555-0001",
                            PositionId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "sarah.johnson@company.com",
                            FirstName = "Sarah",
                            HireDate = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            ManagerId = 1,
                            PhoneNumber = "555-0002",
                            PositionId = 2,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "michael.chen@company.com",
                            FirstName = "Michael",
                            HireDate = new DateTime(2020, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chen",
                            ManagerId = 1,
                            PhoneNumber = "555-0003",
                            PositionId = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Email = "emily.davis@company.com",
                            FirstName = "Emily",
                            HireDate = new DateTime(2020, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            ManagerId = 1,
                            PhoneNumber = "555-0004",
                            PositionId = 6,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            Email = "david.wilson@company.com",
                            FirstName = "David",
                            HireDate = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            ManagerId = 1,
                            PhoneNumber = "555-0005",
                            PositionId = 8,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Email = "james.brown@company.com",
                            FirstName = "James",
                            HireDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            ManagerId = 3,
                            PhoneNumber = "555-0006",
                            PositionId = 4,
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Email = "lisa.garcia@company.com",
                            FirstName = "Lisa",
                            HireDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Garcia",
                            ManagerId = 3,
                            PhoneNumber = "555-0007",
                            PositionId = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            Email = "robert.martinez@company.com",
                            FirstName = "Robert",
                            HireDate = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Martinez",
                            ManagerId = 4,
                            PhoneNumber = "555-0008",
                            PositionId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            Email = "jennifer.taylor@company.com",
                            FirstName = "Jennifer",
                            HireDate = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            ManagerId = 4,
                            PhoneNumber = "555-0009",
                            PositionId = 7,
                            Status = 1
                        });
                });

            modelBuilder.Entity("ERMS.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 250000m,
                            Description = "Chief Executive Officer",
                            IsDeleted = false,
                            Title = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 90000m,
                            Description = "Human Resources Manager",
                            IsDeleted = false,
                            Title = "HR Manager"
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 120000m,
                            Description = "Engineering Team Lead",
                            IsDeleted = false,
                            Title = "Engineering Manager"
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 100000m,
                            Description = "Senior Software Developer",
                            IsDeleted = false,
                            Title = "Senior Developer"
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 65000m,
                            Description = "Junior Software Developer",
                            IsDeleted = false,
                            Title = "Junior Developer"
                        },
                        new
                        {
                            Id = 6,
                            BaseSalary = 95000m,
                            Description = "Sales Team Manager",
                            IsDeleted = false,
                            Title = "Sales Manager"
                        },
                        new
                        {
                            Id = 7,
                            BaseSalary = 55000m,
                            Description = "Sales Rep",
                            IsDeleted = false,
                            Title = "Sales Representative"
                        },
                        new
                        {
                            Id = 8,
                            BaseSalary = 90000m,
                            Description = "Marketing Team Manager",
                            IsDeleted = false,
                            Title = "Marketing Manager"
                        });
                });

            modelBuilder.Entity("ERMS.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1,
                            IsActive = true,
                            PasswordHash = "admin123",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2,
                            IsActive = true,
                            PasswordHash = "manager123",
                            Role = 1,
                            Username = "sarah.j"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3,
                            IsActive = true,
                            PasswordHash = "manager123",
                            Role = 1,
                            Username = "michael.c"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4,
                            IsActive = true,
                            PasswordHash = "manager123",
                            Role = 1,
                            Username = "emily.d"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6,
                            IsActive = true,
                            PasswordHash = "employee123",
                            Role = 2,
                            Username = "james.b"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 7,
                            IsActive = true,
                            PasswordHash = "employee123",
                            Role = 2,
                            Username = "lisa.g"
                        });
                });

            modelBuilder.Entity("ERMS.Models.Employee", b =>
                {
                    b.HasOne("ERMS.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERMS.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERMS.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ERMS.Models.User", b =>
                {
                    b.HasOne("ERMS.Models.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("ERMS.Models.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERMS.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ERMS.Models.Employee", b =>
                {
                    b.Navigation("Subordinates");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("ERMS.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
